// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

type Customer struct {
	ID          int32
	Name        string
	Gender      string
	Birthdate   string
	Birthplace  string
	Province    string
	Regency     string
	District    string
	Village     string
	Address     string
	CitizenID   string
	PassportID  string
	PassportExp string
	CitizenCard string
	Passport    string
	FamilyCard  string
	Photo       string
	RoomType    string
	TravelPkg   string
}

type User struct {
	ID       int32
	Email    string
	Password string
	Role     string
}
